name: Build and Test

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ['', '--no-default-features']
        target: ['x86_64-unknown-linux-gnu', 'i686-unknown-linux-gnu']
    steps:
      - uses: actions/checkout@v1
      - if: ${{ matrix.target == 'i686-unknown-linux-gnu' }}
        name: Install 32-bit system toolchain
        run: sudo apt-get install gcc-multilib -y
      - if: ${{ matrix.target == 'i686-unknown-linux-gnu' }}
        name: Install rust toolchain target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }} ${{ matrix.features }}
      - name: Test
        run: cargo test --verbose --target ${{ matrix.target }} ${{ matrix.features }}
