name: Publish Crate

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  project_display_name: ZwoHash

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "^3.8"
      - name: Pre-Publish Checks
        id: pre_publish_checks
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: python .github/workflows/publish-crate-checks.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.project_display_name }} ${{ steps.pre_publish_checks.outputs.version }}
          body: ${{ fromJson(steps.pre_publish_checks.outputs.changelog) }}
          draft: false
          prerelease: false
      - name: Publish Crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
      - name: Push to release Branch
        run: |
          git push origin +HEAD:release
