name: Publish Crate

on: workflow_dispatch

env:
  project_display_name: ZwoHash

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pre-Publish Checks
        id: pre_publish_checks
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: python3.8 .github/workflows/publish-crate-checks.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.project_display_name }} ${{ steps.pre_publish_checks.outputs.version }}
          body: ${{ fromJson(steps.pre_publish_checks.outputs.changelog) }}
          draft: false
          prerelease: false
      - name: Publish Crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
